version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/hare
    # branches:
    #   only:
    #     - master
    #     - dev
    steps: &steps
      - checkout
      - restore_cache:
          keys:
          - hare-deps-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - hare-deps-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: hare-deps-{{ checksum "yarn.lock" }}
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:11
    working_directory: ~/hare
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git dev:master

workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
